### ISSUE TITLE
Enhancement: group multinomial EMM by response variable in GLMM

### ISSUE THREAD

**Issue by N1X3L** [gamlj/gamlj#254]
When time allows, please consider grouping the Estimated Marginal Means of a multinomially-distributed analysis by the response variable in a Generalized Mixed Model. This feature is already present in the Generalized Linear Model. I've posted screenshots, and attached some output, to highlight the difference. Thank you!
[SchoolExam_Multi.pdf](https://github.com/gamlj/gamlj/files/15505926/SchoolExam_Multi.pdf)
### GLM
![EMM_GLM](https://github.com/gamlj/gamlj/assets/58523957/7de0ad3c-3f81-4200-b9af-bd13e64c4c79)
### GLMM
![EMM_GLMM](https://github.com/gamlj/gamlj/assets/58523957/a6bb689a-c7b5-43c3-a5c8-98d38c8bf464)

**Comment by mcfanda** [comment]
Sure. Hext version will fix it. Thx

**Comment by mcfanda** [comment]
fixed in version 3.3.2 coming out in a few days

**Comment by N1X3L** [comment]
The problem still persists in v. 3.3.3. Please let me know if you can't replicate, and I'll post screenshots. I appreciate you for working on this!

**Comment by mcfanda** [comment]
yes, you 're right. The solution got lost in other updates. Next version will have it (hopefully). Please check it out (next week)

**Comment by N1X3L** [comment]
This is working now. Thank you!!!
